---
- name: "[COMMON] Update hostname"
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: "[COMMON] Update hosts file"
  become: yes
  template:
    src: "templates/common/hosts.j2"
    dest: /etc/hosts
    owner:  root
    group: root
    mode: 0644

- name: "[COMMON] Add deploy key"
  template:
    src: "templates/common/deploy_key.j2"
    dest: "{{ deploy_key_path }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0600

- name: "[COMMON] Update .bashrc"
  become: yes
  copy:
    src: files/bashrc
    dest: /root/.bashrc
    mode: 0755

# Setup NTP/Timezone
- name: "[COMMON] Enable NTP"
  become: yes
  command: timedatectl set-ntp true

- name: "[COMMON] Set timezone"
  become: yes
  timezone:
    name: "{{ ntp_timezone }}"

- name: "[COMMON] Restart cron"
  become: yes
  service:
    name: cron
    state: restarted

# Setup UFW firewall
- name: "[COMMON] Install ufw"
  become: yes
  apt:
    name: "ufw"
    state: present

- name: "[COMMON] UFW: Add SSH rule to"
  become: yes
  ufw:
    rule: allow
    port: "{{ ansible_ssh_port }}"

- name: "[COMMON] UFW: Set incoming policy to deny all"
  become: yes
  ufw:
    direction: incoming
    policy: deny

- name: "[COMMON] UFW: Set outgoing policy to allow all"
  become: yes
  ufw:
    direction: outgoing
    policy: allow

- name: "[COMMON] Enable ufw"
  become: yes
  ufw:
    state: enabled

# Setup auto update
- name: "[COMMON] Install unattended-upgrades"
  become: yes
  apt:
    name: "unattended-upgrades"
    state: present

- name: "[COMMON] Update unattended-upgrades configuration"
  become: yes
  copy:
    src: files/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644

- name: "[COMMON] Update auto-upgrades configuration"
  become: yes
  copy:
    src: files/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644