---
- name: "[DATABASE] Install PostgreSQL"
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-dev

- name: "[DATABASE] install psycopg2"
  become: yes
  pip:
    name: psycopg2

- name: "[DATABASE] PostgreSQL: Update config"
  become: yes
  template:
    src: "templates/database/postgresql.conf.j2"
    dest: "/etc/postgresql/10/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: postgresql restart

- name: "[DATABASE] PostgreSQL: Update pg_hba"
  become: yes
  template:
    src: "templates/database/pg_hba.conf.j2"
    dest: "/etc/postgresql/10/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: postgresql restart

- name: "[DATABASE] PostgreSQL: Create user"
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"

- name: "[DATABASE] PostgreSQL: Create DB"
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_username }}"

- name: "[DATABASE] PostgreSQL: Update pgpass"
  become: yes
  become_user: "{{ app_user }}"
  template:
    src: "templates/database/pgpass.j2"
    dest: "/home/{{ app_user }}/.pgpass"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0600

- name: "[DATABASE] Create backup directory"
  become: yes
  become_user: "{{ app_user }}"
  file:
    path: "/home/{{ app_user }}/backups"
    state: directory
    mode: 0755

- name: "[DATABASE] Enable cron backup"
  become: yes
  become_user: "{{ app_user }}"
  cron:
    name: "DB cron backup"
    minute: "0"
    hour: "3"
    job: "pg_dump {{ db_name }} > /home/{{ app_user }}/backups/$(date '+\\%A').sql"

- name: "[DATABASE] Install pgbouncer"
  become: yes
  apt:
    name: pgbouncer
    state: present

- name: "[DATABASE] Update pgbouncer config"
  become: yes
  template:
    src: "templates/database/pgbouncer.ini.j2"
    dest: "/etc/pgbouncer/pgbouncer.ini"
    owner: postgres
    group: postgres
    mode: 0640
  notify: pgbouncer restart

- name: "[DATABASE] Update pgbouncer users"
  become: yes
  template:
    src: "templates/database/userlist.txt.j2"
    dest: "/etc/pgbouncer/userlist.txt"
    owner: postgres
    group: postgres
    mode: 0640
  notify: pgbouncer restart

- name: "[DATABASE] Flush handlers"
  meta: flush_handlers