---
- name: "[USER] Create  user"
  become: yes
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    create_home: yes

- name: "[USER] Update .bashrc"
  become: yes
  become_user: "{{ app_user }}"
  copy:
    src: files/bashrc
    dest: /home/{{ app_user }}/.bashrc
    mode: 0755

- name: "[USER] Create .ssh directory"
  become: yes
  become_user: "{{ app_user }}"
  file:
    path: "/home/{{ app_user }}/.ssh"
    state: directory
    mode: 0755

- name: "[USER] Create app directory"
  become: yes
  become_user: "{{ app_user }}"
  file:
    path: "/home/{{ app_user }}/application"
    state: directory
    mode: 0755

- name: "[USER] Add deploy key"
  become: yes
  become_user: "{{ app_user }}"
  template:
    src: "templates/common/deploy_key.j2"
    dest: "/home/{{ app_user }}/.ssh/deploy.key"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0600